name: SigTheDog
favicon: null
layout_spectrum: 0.21366848051548004
typography_spectrum: 0.32950011477805674
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9818445397540927
  lightness: 0.291473570978269
  saturation: 0.3670011044014245
  rhythmicContrast: 0.07375608710572124
purpose: []
