name: SigTheDog
favicon: null
layout_spectrum: 0.21366848051548004
typography_spectrum: 0.32950011477805674
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#53637e'
    - '#482604'
    - '#956b43'
    - '#94a2c2'
  brandStrength: 0.5
  lightness: 0.291473570978269
  saturation: 0.3670011044014245
  rhythmicContrast: 0.07375608710572124
purpose: []
